/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_resample_Resample */

#ifndef _Included_cn_com_lasong_media_Resample
#define _Included_cn_com_lasong_media_Resample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_lasong_media_Resample
 * Method:    stereo2mono
 * Signature: (Ljava/nio/ByteBuffer;[BI)V
 */
JNIEXPORT void JNICALL Java_cn_com_lasong_media_Resample_stereo2mono
        (JNIEnv *, jclass, jobject, jbyteArray, jint);

/*
 * Class:     cn_com_lasong_media_Resample
 * Method:    mix
 * Signature: (Ljava/nio/ByteBuffer;[B)V
 */
JNIEXPORT void JNICALL Java_cn_com_lasong_media_Resample_mix
        (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     cn_com_lasong_media_Resample
 * Method:    resample
 * Signature: ([B[BF)I
 */
JNIEXPORT jint JNICALL Java_cn_com_lasong_media_Resample_resample
        (JNIEnv *, jclass, jbyteArray, jbyteArray, jfloat);

/*
 * Class:     cn_com_lasong_media_Resample
 * Method:    init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_com_lasong_media_Resample_init
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_com_lasong_media_Resample
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_com_lasong_media_Resample_destroy
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
